### ISSUE TITLE
SecurityException after device is unlocked from password protected lock

### ISSUE THREAD

**Issue by vonfrahma** [googlesamples/android-Camera2Video#23]
The application encounters fatal exception when the following is performed:
1) Set mobile device to require password after Screen Lock
2) Start application, confirm camera preview
3) Screen lock device (via hw switch)
4) Unlock screen (via hw switch)
5) Enter password 
6) Application crashes

This issue cannot be replicated when Screen Lock does not require password.
This is encountered in when using android API 23.

It seems permission is revoked during password protected lock.
'hasPermissionGranted' returns true (PERMISSION_GRANTED) but camera device operation fails when performed after password protected screen lock.

`
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: XXXXXXX PID: 30056
    java.lang.SecurityException: Lacking privileges to access camera service
            at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:108)
            at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
            at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
            at java.lang.reflect.Proxy.invoke(Proxy.java:393)
            at $Proxy1.cancelRequest(Unknown Source)
            at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
            at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
            at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514)
            at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:61
`

**Comment by vonfrahma** [comment]
uses-permission comes after application tag in local copy.
Switched position and issue no longer occur.

**Comment by nyelito** [comment]
Hey I'm still getting this error even with uses-permissions before the application tag. Is there anything else you changed?

**Comment by yudikarma** [comment]
hi @vonfrahma  you solve this bug ? please tell me how to do. thanks
