### ISSUE TITLE
 Sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by thizisarun** [googlesamples/android-Camera2Video#28]
Hi all this bug is not related to this project, sorry for posting here but its related to camera2. I am taking picture by using camera2. While i am taking picture i am getting below exception 

`Handler (android.os.Handler) {18b2b23b} sending message to a Handler on a dead thread
                                                                     java.lang.IllegalStateException: Handler (android.os.Handler) {18b2b23b} sending message to a Handler on a dead thread
                                                                         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                         at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                         at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                         at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                         at android.os.Handler.post(Handler.java:326)
                                                                         at android.hardware.camera2.dispatch.HandlerDispatcher.dispatch(HandlerDispatcher.java:61)
                                                                         at android.hardware.camera2.dispatch.MethodNameInvoker.invoke(MethodNameInvoker.java:88)
                                                                         at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:176)
                                                                         at android.hardware.camera2.impl.CameraCaptureSessionImpl$UnconfigureDrainListener.onDrained(CameraCaptureSessionImpl.java:709)
                                                                         at android.hardware.camera2.utils.TaskDrainer$1.run(TaskDrainer.java:197)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)`

I dont know why i am getting this. My device details
 **Device Name : Samsung Tab 10 Inch
 Model Number : SM-P601
 OS : Android 5.1.1**

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
