### ISSUE TITLE
Crashes on Xiaomi Redmi 4 OS 6.0.1

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-Camera2Video#37]
App crashes when I press Stop button

`02-13 17:25:17.612 31798-623/com.example.android.camera2video E/CameraDeviceGLThread-0: Received exception on GL render thread: 
                                                                                        java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
                                                                                            at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
                                                                                            at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
                                                                                            at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:727)
                                                                                            at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
02-13 17:25:17.612 31798-623/com.example.android.camera2video I/CameraDeviceState: Legacy camera service transitioning to state ERROR
02-13 17:25:17.754 31798-31798/com.example.android.camera2video E/MediaRecorder: stop failed: -1007
02-13 17:25:17.754 31798-31798/com.example.android.camera2video D/AndroidRuntime: Shutting down VM
02-13 17:25:17.755 31798-31798/com.example.android.camera2video E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.example.android.camera2video, PID: 31798
                                                                                  java.lang.RuntimeException: stop failed.
                                                                                      at android.media.MediaRecorder.stop(Native Method)
                                                                                      at com.example.android.camera2video.Camera2VideoFragment.stopRecordingVideo(Camera2VideoFragment.java:679)
                                                                                      at com.example.android.camera2video.Camera2VideoFragment.onClick(Camera2VideoFragment.java:313)
                                                                                      at android.view.View.performClick(View.java:5207)
                                                                                      at android.view.View$PerformClick.run(View.java:21177)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by JasonZhu19910601** [comment]
I have the same error.

**Comment by rspq** [comment]
Same crash on Moto Z Play running 6.0.1.

It says something about the utter awfulness of Camera2 that even Google cannot produce working samples for it.

**Comment by Barazu** [comment]
It actually has an easy fix.
Add this code to the stopRecordingVideo method:
 ```
try {
            mPreviewSession.abortCaptures();
        } catch (CameraAccessException e) {
            e.printStackTrace();
        }

        Timer timer = new Timer();
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                mMediaRecorder.stop();
                mMediaRecorder.reset();
            }
        };
        timer.schedule(timerTask,30);
```
The reason for the exception is explained here : [](https://stackoverflow.com/a/34153954).
The simplest workaround (that I found at least) is to call mPreviewSession.abortCaptures(); and set a short delay before calling  mMediaRecorder.stop(); as abortCaptures() may take time to execute. 
Hope this helps!

**Comment by anonym24** [comment]
what about 1007 failed but with MediaProjection (not camera)

https://stackoverflow.com/questions/45266016/screen-recording-stop-failed-and-failure-delivering-result-resultinfo

**Comment by anonym24** [comment]
https://github.com/googlesamples/android-Camera2Video/issues/86
https://issuetracker.google.com/issues/111433520
https://stackoverflow.com/questions/51332386/mediarecorder-and-videosource-surface-stop-failed-1007-a-serious-android-bug

many devices just don't work with Surface input source (MediaRecorder, MediaCodec)

MediaCodec works ok only with Surface and OpenGL ES but not with lockHardwareCanvas

**Comment by anonym24** [comment]
@Barazu it only `may` fix issue with crash (Exception 1007), but video file's size is only 19 kilobytes, so frames just weren't recorded into video file (.mp4 container)

it even doesn't always fix that crash

so there is no solution

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
