### ISSUE TITLE
android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error

### ISSUE THREAD

**Issue by FanYimin** [googlesamples/android-Camera2Video#38]
02-14 18:55:46.506 17115-17115/com.example.android.camera2video E/CameraCaptureSession: Session 1: Exception while stopping repeating: 
                                                                                        android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
                                                                                            at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
                                                                                            at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
                                                                                            at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:328)
                                                                                            at com.example.android.camera2video.Camera2VideoFragment.closePreviewSession(Camera2VideoFragment.java:669)
                                                                                            at com.example.android.camera2video.Camera2VideoFragment.startPreview(Camera2VideoFragment.java:491)
                                                                                            at com.example.android.camera2video.Camera2VideoFragment.stopRecordingVideo(Camera2VideoFragment.java:689)
                                                                                            at com.example.android.camera2video.Camera2VideoFragment.onClick(Camera2VideoFragment.java:313)
                                                                                            at android.view.View.performClick(View.java:4851)
                                                                                            at android.view.View$PerformClick.run(View.java:20016)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5481)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by FanYimin** [comment]
xiaomi meizu both get crushed

**Comment by fxp** [comment]
moto X(2nd generation, 5.0) crashs with the same error

**Comment by fxp** [comment]
I got a fix from [stackoverflow](http://stackoverflow.com/questions/27907090/android-camera-2-api). Basically stopping capturing video before close recorder, but don't know why exactly.

**Comment by Barazu** [comment]
Answered here: https://github.com/googlesamples/android-Camera2Video/issues/37
While stopping capturing video does prevent the crash, an error is still thrown and the app sometimes get stuck (not sure if on every phone, but it did on mine). Delaying the stop of the recorder fixes that.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
