### ISSUE TITLE
Crashes when stopping repeating

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-Camera2Video#39]
I directly downloaded the source code and when I try to finish recording and watch preview, it causes an error and app suddenly stops. Actually, when I look at previous changes, there is a change in closePreviewSession and I think it may cause an error. 

Session 1: Exception while stopping repeating: 
                                                                                      android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
                                                                                          at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1987)
                                                                                          at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:894)
                                                                                          at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:373)
                                                                                          at com.example.android.camera2video.Camera2VideoFragment.closePreviewSession(Camera2VideoFragment.java:675)
                                                                                          at com.example.android.camera2video.Camera2VideoFragment.startPreview(Camera2VideoFragment.java:497)
                                                                                          at com.example.android.camera2video.Camera2VideoFragment.stopRecordingVideo(Camera2VideoFragment.java:695)
                                                                                          at com.example.android.camera2video.Camera2VideoFragment.onClick(Camera2VideoFragment.java:317)
                                                                                          at android.view.View.performClick(View.java:5210)
                                                                                          at android.view.View$PerformClick.run(View.java:21328)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by devilabhi** [comment]
Did you get any soln for this?

**Comment by masheransari** [comment]
https://stackoverflow.com/a/35739021/7839888
