### ISSUE TITLE
Crash after stop recording

### ISSUE THREAD

**Issue by tzutalin** [googlesamples/android-Camera2Video#46]
Device: ZenFone 3 Max 
OS: Android M

```
03-20 17:24:52.634 11692        RequestThread-0  E  Timed out while waiting for request to complete.
03-20 17:24:52.635 11692       CaptureCollector  W  Preview buffers dropped for request: 1
03-20 17:24:52.635 11692      CameraDeviceState  E  Cannot receive result while in state: 0
03-20 17:24:52.635 11692                         E  Cannot receive result while in state: 0
03-20 17:24:52.642 11692                         E  Cannot receive result while in state: 0
03-20 17:24:52.674 11695                         I  Legacy camera service transitioning to state CAPTURING
03-20 17:24:52.675 11695                         E  Cannot call capture while in state: 0
03-20 17:24:52.682 11695                 Adreno  I  DequeueBuffer: dequeueBuffer failed
03-20 17:24:52.683 11695 CameraDeviceGLThread-0  E  Received exception on GL render thread:
03-20 17:24:52.683 11695                         E  java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
03-20 17:24:52.683 11695                         E      at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
03-20 17:24:52.683 11695                         E      at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
03-20 17:24:52.683 11695                         E      at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:727)
03-20 17:24:52.683 11695                         E      at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
03-20 17:24:52.683 11695                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
03-20 17:24:52.683 11695                         E      at android.os.Looper.loop(Looper.java:148)
03-20 17:24:52.683 11695                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by tzutalin** [comment]
Same as #37

**Comment by skynetlabz** [comment]
We have made a pull request with this crash resolved.

**Comment by 0x7962** [comment]
I have the same problem on my custom device(API 21), i found solution at there [https://stackoverflow.com/questions/27907090/android-camera-2-api/32621903#32621903](url),
it works for me.

**Comment by madhurgoel** [comment]
plz reffer to issue #57

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
