### ISSUE TITLE
Handler (android.os.Handler) {12b2215b} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by JackyBower** [googlesamples/android-Camera2Video#52]
/**
     * Stops the background thread and its {@link Handler}.
     */
    private void stopBackgroundThread() {
        mBackgroundThread.quitSafely();
        try {
            mBackgroundThread.join();
            mBackgroundThread = null;
            mBackgroundHandler = null;
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
`
Handler (android.os.Handler) {12b2215b} sending message to a Handler on a dead thread
                                                                             java.lang.IllegalStateException: Handler (android.os.Handler) {12b2215b} sending message to a Handler on a dead thread
                                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                                 at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                 at android.os.Handler.sendMessageAtFrontOfQueue(Handler.java:623)
                                                                                 at android.hardware.camera2.legacy.RequestThreadManager.quit(RequestThreadManager.java:941)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.close(LegacyCameraDevice.java:444)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.finalize(LegacyCameraDevice.java:468)
                                                                                 at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
                                                                                 at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
                                                                                 at java.lang.Thread.run(Thread.java:818)`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
