### ISSUE TITLE
on resume then stop getting below error

### ISSUE THREAD

**Issue by empasssdk** [googlesamples/android-Camera2Video#76]
**on resume then stop getting below **error****

Process: com.example.android.camera2video, PID: 28009
                                                                                  java.lang.IllegalStateException
                                                                                      at android.media.MediaRecorder.stop(Native Method)
                                                                                      at com.example.android.camera2video.Camera2VideoFragment.stopRecordingVideo(Camera2VideoFragment.java:682)
                                                                                      at com.example.android.camera2video.Camera2VideoFragment.onClick(Camera2VideoFragment.java:312)
                                                                                      at android.view.View.performClick(View.java:4785)
                                                                                      at android.view.View$PerformClick.run(View.java:19884)
                                                                                      at android.os.Handler.handleCallback(Handler.java:746)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
